version: '3'

services:
  app:
    build: .
    environment:
      DEBUG: 1 # 1=true, 0=false
      ALLOWED_HOSTS: "127.0.0.1" # split by ',' do not use spaces. eg: "127.0.0.1,192.168.0.1,192.168.0.2"

      SECRET_KEY: verysecurekey
      SUPERUSER_USERNAME: admin
      SUPERUSER_EMAIL: admin@admin.com
      SUPERUSER_PASSWORD: admin

      DB_ENGINE: django.db.backends.postgresql_psycopg2 # or postgresql
      DB_NAME: mydatabase
      DB_USER: mydatabaseuser
      DB_PASS: mypassword
      DB_HOST: db # same name as the postgres service
      DB_PORT: 5432

    ports:
      - 8008:8000
    links:
      - db

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword

    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
