# Generated by Django 4.1.5 on 2023-01-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_colors(apps, schema_editor):
    Color = apps.get_model('car_sales', 'CarColor')
    colors = ('yellow', 'blue', "gray")
    for color in colors:
        Color.objects.create(name=color)


def create_models(apps, schema_editor):
    Color = apps.get_model('car_sales', 'CarModel')
    colors = ("hatch", "sedan", "convertible")
    for color in colors:
        Color.objects.create(name=color)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Data de criação')),
                ('alteration',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Data de modificação')),
                ('active',
                 models.BooleanField(default=True,
                                     verbose_name='Ativo?')),
                ('description',
                 models.CharField(blank=True,
                                  max_length=200,
                                  null=True,
                                  verbose_name='Descrição')),
                ('name',
                 models.CharField(max_length=200,
                                  verbose_name='Name')),
                ('address',
                 models.CharField(max_length=200,
                                  verbose_name='Address')),
                ('phone',
                 models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='car_sales.person')),
            ],
            options={
                'abstract': False,
            },
            bases=('car_sales.person',
                  ),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Data de criação')),
                ('alteration',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Data de modificação')),
                ('active',
                 models.BooleanField(default=True,
                                     verbose_name='Ativo?')),
                ('description',
                 models.CharField(blank=True,
                                  max_length=200,
                                  null=True,
                                  verbose_name='Descrição')),
                ('name',
                 models.CharField(max_length=255)),
                ('price',
                 models.DecimalField(decimal_places=2,
                                     max_digits=8)),
                ('color',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='car_sales.carcolor')),
                ('model',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='car_sales.carmodel')),
                ('owner',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='cars',
                                   to='car_sales.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('purchase_date',
                 models.DateField()),
                ('car',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='car_sales.car')),
                ('salesperson',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to=settings.AUTH_USER_MODEL)),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='car_sales.customer')),
            ],
            options={
                'permissions': [('can_sell',
                                 'Can sell cars')],
            },
        ),
        migrations.RunPython(create_colors),
        migrations.RunPython(create_models),
    ]
